global:
  scrape_interval: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: prometheus-stack

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: self
    static_configs:
      - targets: [node_exporter:9100]
  - job_name: pushgateway
    static_configs:
      - targets: [pushgateway:9091]
  - job_name: blackbox
    static_configs:
      - targets: [blackbox_exporter:9115]
  - job_name: blackbox_http
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
